# Generated by Django 5.0.2 on 2024-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
