# Generated by Django 5.0.2 on 2024-02-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_booking_service_alter_booking_service_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
